Requisitos no funcionales
GDUMA/reservas-esqueleto pull request #14
Opened 2021-03-24 18:44 UTC by jann9

Acepto  sugerencias.

2021-03-25 03:45 UTC, arturoaguileraa commented
Todo guay Mario, quizás algunos párrafos con el guion sin espaciar hace que no se lea bien el .md
Además hay como dos archivos modificados, se ha subido como un submódulo del README del master, no se si lo ha hecho Visual Studio de manera automática. Por lo demás lo veo super bien.

2021-03-26 08:41 UTC, tomgreef requested changes

2021-03-26 08:41 UTC, tomgreef commented on README.md
>  Esta sección especifica los requisitos funcionales de sistema que el futuro software debe tener en su entorno. Se aconseja inclur al final de esta subsección, tras describir los requisitos funcionale
Diría que puedes borrar esta sección completamente. Asegurate de corregir el índice del documento cuando lo haces y la enumeración

2021-03-26 08:41 UTC, tomgreef commented on README.md
> +| R36 | Control de  rendimiento	| Si  el rendimiento decae del 80%  restringirá el acceso	| Fundamental  |  	| No Funcional |
me gusta la idea, quizas podemos ponerlo como _Deseable_ o _Opcional_ para que lo podamos implementar con estadísticas, ya que este rendimiento lo vamos a calcular viendo los milisegundos entre operaciones

2021-03-26 08:41 UTC, tomgreef commented on README.md
> +| R35 | Soporte de conexión	| El sistema debe soportar la conexion de varias terminales al mismo tiempo y de un número razonable de usuarios	| Fundamental  |  	| No Funcional |
Parece más un RF antes que un RNF.

2021-03-26 08:41 UTC, tomgreef commented on README.md
> +| R42 | Fiabilidad	| El software debe funcionar de manera fiable	| Fundamental  |  	| No Funcional |
Muy ambiguo, tienes algunas ideas?

2021-03-26 08:41 UTC, tomgreef commented on README.md
> +| R43 | Cierre de  sesión	| En caso de cierre de sesión inesperado se debe guardar el último cambio confirmado	| Opcional  |  	| No Funcional |
¿Cambio confirmado? ¿Te refieres al carrito de pedidos?

2021-03-26 08:41 UTC, tomgreef commented on README.md
> +| R45 | Mantenimientos  programados	| Los mantenimientos del sistema deben estar programados y ser de corta duración	| Fundamental  |  	| No Funcional |
No podemos hacer esto, ya que es un esqueleto y por ello no tiene mantenimiento. Quizás si en un futuro lo vas usar para tu aplicación, si podrías añadirlo

2021-03-26 08:41 UTC, tomgreef commented on README.md
>  Esta sección establece requisitos no funcionales relacionados con la calidad que deben presentar las funcionales del software.
Borraría este comentario y dejaría solo el título.

2021-03-26 08:41 UTC, tomgreef commented on README.md
> +-El sistema debe soportar la conexion de varias terminales al mismo tiempo y encargarse de un  número razonable de usuarios consistentemente y sin problemas
Tienes que poner espacio entre los guiones - para que se indexe como lista de puntos.

2021-03-26 08:41 UTC, tomgreef commented on README.md
> +-El software debe funcionar de manera fiable.
Ambiguo

2021-03-26 08:41 UTC, tomgreef commented on README.md
Estas secciones los podemos completar cuando empezamos con la implementación, ya que sería nuestra guía para usar este esqueleto en un futuro.

2021-03-28 19:04 UTC, jann9 commented on README.md
> +| R43 | Cierre de  sesión	| En caso de cierre de sesión inesperado se debe guardar el último cambio confirmado	| Opcional  |  	| No Funcional |
Sí, que no lo pierdas si se te cae el internet o cierras la ventana sin querer.

2021-03-28 19:05 UTC, jann9 commented on README.md
> +-El software debe funcionar de manera fiable.
Tienes razón, no se me ocurre qué poner a parte de que el sistema  tiene  que  funcionar bien sin bugs  y  sin errores.

2021-03-29 11:05 UTC, tomgreef commented on README.md
> +-El software debe funcionar de manera fiable.
Pues quitalo, ya que cualquier sistema software debe ser fiable

2021-03-29 11:06 UTC, tomgreef commented
@jann9 necesitas hacer los cambios y hacer un nuevo commit + push. Avisa si no te va bien

2021-03-29 15:40 UTC, jann9 commented
> @jann9 necesitas hacer los cambios y hacer un nuevo commit + push. Avisa si no te va bien
Creo que  ya lo he hecho, me falta arreglar  lo que  me ha dicho Arturo  de los dos  archivos

2021-03-29 16:09 UTC, tomgreef commented
Bro, tienes que resolver las cosas que te comenté para poder hacer el merge 💪

2021-03-29 18:54 UTC, tomgreef approved these changes

2021-03-29 19:02 UTC, merged

2021-03-29 19:05 UTC, jann9 commented
He resuelto un conflicto, he unificado la tabla de funcionales y no funcionales, eliminado los  apéndices y arreglado la sangría