Service Card and My Services
GDUMA/reservas-esqueleto pull request #30
Opened 2021-05-11 11:09 UTC by AleReyLeyva

Dejen sus opiniones por aquí :smile:

2021-05-11 11:28 UTC, tomgreef requested changes
Si ves algo que no estás de acuerdo con dímelo bro 🚀💪🏼

2021-05-11 11:28 UTC, tomgreef commented on app/src/views/MyServices.tsx
> +  return (
Esto es una vista, por lo que recomiendo los siguientes cambios:
- Usar Fragment tags
- Dentro del fragment vas a importar 2 componentes: Al principio Header.tsx y al final Footer.tsx
- En medio de estos dos componentes puedes añadir este div, aunque creo que estaría mejor que lo encapsulases en un main o section
- el class name del div principal esta bien?

2021-05-12 16:36 UTC, tomgreef reviewed
👍🍻

2021-05-12 16:36 UTC, tomgreef approved these changes

2021-05-13 15:14 UTC, Naxetee approved these changes

2021-05-13 15:22 UTC, merged